# Generated by Django 5.1.4 on 2024-12-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_comment_author_alter_message_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
